#### Real life data handling

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
# print(sales_data[:3, 1:])
# Calculate the total sales of the year
print(np.sum(sales_data[:, 1:], axis=0)*12)

# find minimum sale in each month
print(np.min(sales_data[:, 1:], axis=1))

# find the average sales of the restuarant
print(np.mean(sales_data[:, 1:], axis=1))

# find cumsum
print(np.cumsum(sales_data[:, 1:], axis=1)) 

# Vectrize
restuarantType = np.array(['paradise Biryani', 'beijing Bites', 'Pizza Hub', 'Burger Point', 'Chai Point'])
vactorize = np.vectorize(str.capitalize)
print(vactorize(restuarantType))

[ 9720000 11340000 13020000 14880000]
[150000 120000 200000 180000 160000]
[200000. 152500. 247500. 225000. 195000.]
[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
['Paradise biryani' 'Beijing bites' 'Pizza hub' 'Burger point'
 'Chai point']
