## Learn NumPy with Chai Aur Code

In [1]:
import numpy as np

#### Creating NumPy Array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


#### What is the difference between Python List and NumPy Array

In [4]:
py_list = [1, 2, 3, 4, 5]
print("Python List:", py_list * 2)  # List multiplication
NumPy_array = np.array(py_list)
print("NumPy Array:", NumPy_array * 2)  # NumPy array multiplication it will multiply each element by 2

Python List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy Array: [ 2  4  6  8 10]


#### Note the time Between list and array

In [48]:
import time
start_time = time.time()
lst = [i for i in range(100000)]
end_time = time.time()
print("Time taken for Python List:", end_time - start_time)

start_time = time.time()
arr = np.arange(100000)
end_time = time.time()
print("Time taken for NumPy Array:", end_time - start_time)

Time taken for Python List: 0.02058887481689453
Time taken for NumPy Array: 0.0009832382202148438


#### Creating Array from scratch

In [62]:
# Zero-dimensional array
zeros = np.zeros((2, 3)) # here 2 is the number of rows and 3 is the number of columns
print("Zero Array:\n", zeros)

# One-dimensional array
ones = np.ones((3,4))  # 3 is the number of elements in the array
print("One Array: \n", ones)

# Constant-dimensional array
full_array = np.full((2, 3), 7)  # 2 rows and 3 columns filled with 7
print("Full Array:\n", full_array)

# Random array
random_array = np.random.random((2, 3))  # 2 rows and 3 columns with random values
print("Random Array:\n", random_array)

# Sequence array
sequence_array = np.arange(0, 10, 2)  # Start at 0, stop at 10, step by 2
print("Sequence Array:", sequence_array)

# Identity matrix
identity_matrix = np.eye(3)  # 3x3 identity matrix
print("Identity Matrix:\n", identity_matrix)

# Randint array
randint_array = np.random.randint(0, 10, (2, 3)) # 2 rows and 3 columns with random integers between 0 and 10
print("Random Integer Array:\n", randint_array)

Zero Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
One Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]]
Random Array:
 [[0.75412639 0.47262525 0.26336359]
 [0.23078209 0.48531714 0.03024329]]
Sequence Array: [0 2 4 6 8]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Integer Array:
 [[3 0 1]
 [0 0 9]]


#### Vector, Matrix, and Tensor

In [ ]:
vector = np.array([1, 2, 3])  # 1D array
print("Vector:", vector)

matrix = np.array([[1, 2], [3, 4]])  # 2D array
print("Matrix:\n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor:\n", tensor)  # 3D array

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions of Tensor: 3


#### Array Properties 

In [64]:
# Array Properties
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array Shape:", arr.shape)  # returns the shape of the array in the form (rows, columns)
print("Array Dimension:", arr.ndim)  # returns the number of dimensions
print("Array Size:", arr.size)  # returns the total number of elements in the array
print("Array Data Type:", arr.dtype)  # returns the data type of the elements in the array
print("Array Item Size:", arr.itemsize)  # returns the size of each element in bytes
print("Array Memory Layout:", arr.flags)  # returns the memory layout of the array

Array Shape: (2, 3)
Array Dimension: 2
Array Size: 6
Array Data Type: int64
Array Item Size: 8
Array Memory Layout:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



#### Array Reshaping

In [ ]:
# Array Reshaping
arr_2 = np.arange(12)  # Create a 1D array with 12 elements
print("Original Array:", arr_2)

reshaped_arr = arr_2.reshape((3, 4))  # Reshape to 3 rows and 4 columns
print("Reshaped Array:\n", reshaped_arr)

# Flattening the array
flattened_arr = reshaped_arr.flatten()  # Convert to 1D array
print("Flattened Array:", flattened_arr)

# ravel method
raveled_arr = reshaped_arr.ravel()  # ravel returns view instead of copy
print("Raveled Array:", raveled_arr)

# Transpose the array
transposed_arr = reshaped_arr.T  # Transpose the array
print("Transposed Array:\n", transposed_arr)

# Concatinate two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_array = np.concatenate((arr1, arr2), axis=0)  # Concatenate along rows
print("Concatenated Array:\n", concatenated_array)

# axis=0 → 🔽 down columns
# axis=1 → ▶️  across rows

# Stack horizontally and vertically
stacked_array_h = np.hstack((arr1, arr2))  # Stack horizontally
print("Stacked Horizontally:\n", stacked_array_h)
stacked_array_v = np.vstack((arr1, arr2))  # Stack vertically
print("Stacked Vertically:\n", stacked_array_v)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Concatenated Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacked Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]
Stacked Vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### important NumPy indexing and slicing 

In [ ]:
# Create a 3x3 array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original Array:\n", a)

# 1. Access specific element (row 0, column 1)
print("\nElement at a[0, 1]:", a[0, 1])  # Output: 2

# 2. Get all rows of column 1
print("\nAll rows, column 1:\n", a[:, 1])  # Output: [2 5 8]

# 3. Slice rows 1 to end, columns 0 to 1
print("\nRows 1 to end, columns 0 and 1:\n", a[1:, :2])
# Output:
# [[4 5]
#  [7 8]]

# 4. Boolean indexing: elements greater than 3
print("\nElements greater than 3:\n", a[a > 3])
# Output: [4 5 6 7 8 9]

# 8. Conditional replacement (where > 5, set to 99)
print("\nReplace values > 5 with 99:\n", np.where(a > 5, 99, a))

# 9. Check if any element > 8
print("\nAny element > 8:", np.any(a > 8))  # True

# 10. Check if all elements < 10
print("All elements < 10:", np.all(a < 10))  # True


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at a[0, 1]: 2

All rows, column 1:
 [2 5 8]

Rows 1 to end, columns 0 and 1:
 [[4 5]
 [7 8]]

Elements greater than 3:
 [4 5 6 7 8 9]

Replace values > 5 with 99:
 [[ 1  2  3]
 [ 4  5 99]
 [99 99 99]]

Any element > 8: True
All elements < 10: True
