## NumPy Array Operations

In [9]:
import numpy as np

#### Indexing and Slicing in NumPy

In [8]:
array = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(array[1:4])
print(array[1:4:2])
print(array[-3])

# 2D Arrays Indexing and Slicing
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
print(array_2d[2,1])
print(array_2d[:,1])
print(array_2d[2,:])

[1 2 3]
[1 3]
7
8
[2 5 8]
[7 8 9]


#### Sorting

In [12]:
unsorted = np.array([3, 1, 2, 5, 4])
print(np.sort(unsorted))  # Sorts the array

# sort 2d array
unsorted_2d = np.array([[2,3,7],
                        [1,5,4],
                        [6,9,8]])
print(np.sort(unsorted_2d, axis=1), '\n')  # Sorts each row
print(np.sort(unsorted_2d, axis=0))  # Sorts each column

[1 2 3 4 5]
[[2 3 7]
 [1 4 5]
 [6 8 9]] 

[[1 3 4]
 [2 5 7]
 [6 9 8]]


#### Filtering

In [32]:
numbers = np.array([43,2,24,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]  # Selects even numbers
print(even_number)

# Mask Filtering
mask = numbers > 10
print(numbers[mask])  # Selects numbers greater than 10

# Fancy Indexing
indices = [1, 2, 4]
print(numbers[indices])  # Selects elements at indices 1, 2, and 4

# Where Function
where = np.where(numbers > 10) 
print(numbers[where])  # Returns indices of elements greater than 10

changeElement = np.where(numbers > 5, 'true', 'false')
print(changeElement)  # Changes elements greater than 4 to 100  
# How where works
new_arr = np.array([])  # Initialize an empty array
for number in numbers:
    if number > 5:
        new_arr = np.append(new_arr, 'true')
    else:
        new_arr = np.append(new_arr, 'false')
print(new_arr)  # Shows how the where function works in a loop

[ 2 24  4  6  8 10]
[43 24]
[ 2 24  5]
[43 24]
['true' 'false' 'true' 'false' 'false' 'true' 'true' 'true' 'true' 'true']
['true' 'false' 'true' 'false' 'false' 'true' 'true' 'true' 'true' 'true']


#### Adding and removing data

In [ ]:
# this is wrong way in this way only element will take it as a addition operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
# print(arr1 + arr2) 

print(np.concatenate((arr1, arr2)))

# Array Compatibility
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([1,2,3])
print('Shape: ', a.shape == b.shape == c.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[ True False False]


3
